development:
  database: Renters_ke
  username: postgres
  password: ridwan
  adapter: postgresql

test:
  adapter: postgresql
  encoding: unicode
  database: Renters_ke tests
  pool: 5
  username: postgres
  password: ridwan
  port: 5432

